# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Commit-test

on:
  push:
    branches: [CI/CD]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        
        
        
    
    steps:
    - name: create secrest json
    - run: cd ~/fitup 
    - run: echo -e ´{
                        "key": "65ce9537a1545dc10439d61cc9391fb10395108671090c0bb81ee0750353f53a",
                        "ropsten_url": "https://speedy-nodes-nyc.moralis.io/e52174e56135b1758cdb4ebf/eth/ropsten",
                        "mumbai_url": "https://speedy-nodes-nyc.moralis.io/e52174e56135b1758cdb4ebf/polygon/mumbai",
                        "binance_testnet_url": "https://speedy-nodes-nyc.moralis.io/e52174e56135b1758cdb4ebf/bsc/testnet",
                        "arbitrum_testnet_url": "https://speedy-nodes-nyc.moralis.io/e52174e56135b1758cdb4ebf/arbitrum/testnet",
                        "etherscan_key": "GMPUDI2FP4R6EU2QWJIX6TTHI9QBB2AFA7",
                        "mumbaiscan_key": "8K2TI38Y9WGAJPV9RGVCU2HMHR73DJGYYM",
                        "bscscan_key": "UP9RUFGWCJETZ7T3STI4QWYQJC6HAK89K9",
                        "arbiscan_key": "FGGPJ5NWBXKB6FHX7WJ3NGPQS5UETUEGJY"}´ >> secrets.json
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        # cache-dependency-path: ./package-lock.json

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - run: npm install
    - run: npm run build --if-present
    - run: npx hardhat test
